# Generated by Django 3.2 on 2021-05-19 10:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Name of product:')),
                ('color', models.CharField(max_length=100, verbose_name='Color of the product')),
                ('desc', models.TextField(verbose_name='Full Description:')),
                ('price', models.PositiveIntegerField(verbose_name='Price')),
                ('sale', models.BooleanField(verbose_name='Sale')),
                ('price_in_sale', models.PositiveIntegerField(blank=True, help_text='if sale is not true,You do not need to input smth to this .if vice versa,it is mandatory ', null=True, verbose_name='Price in sale:')),
                ('quantity', models.PositiveIntegerField()),
                ('img', models.ImageField(upload_to='', verbose_name='Main Image')),
                ('size', models.CharField(max_length=100, verbose_name='Size of the product')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.CharField(choices=[('Fashion & Beauty', 'Fashion & Beauty'), ('Kids & Babies Clothes', 'Kids & Babies Clothes'), ('Men & Women  Clothes', 'Men & Women  Clothes'), ('Gadgets & Accessories', 'Gadgets & Accessories'), ('Electronics & Accessories', 'Electronics & Accessories')], max_length=100, verbose_name='Category:')),
                ('brand', models.CharField(max_length=100, verbose_name='Mahsulot Brandi:')),
                ('v', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('bought', models.PositiveIntegerField(blank=True, default=1, null=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
