# Generated by Django 3.2 on 2021-05-24 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_products_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='sale',
            field=models.BooleanField(blank=True, verbose_name='Sale'),
        ),
    ]
