# Generated by Django 3.2 on 2021-05-24 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_products_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='sale',
            field=models.BooleanField(default=False, verbose_name='Sale'),
        ),
    ]
