# Generated by Django 3.2 on 2021-05-31 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_auto_20210531_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='name',
            field=models.CharField(default='AA', max_length=500),
            preserve_default=False,
        ),
    ]
